# informa pro h2 salvar em arquivo, não em memória
spring.datasource.url=jdbc:h2:file:./data/persistencia
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# o hibernate cria/atualiza as tabelas automaticamente
# "update" preserva os dados entre reinicializações
spring.jpa.hibernate.ddl-auto=update

#mostra o sql gerado no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# o console web do h2, permite inspecionar o banco pelo navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.application.name=Persistencia
