# a url de conexão com o postgresql
# formato: jdbc:postgresql://host:porta/nome_do_banco
spring.datasource.url=${DB_URL}

# driver do postgresql, spring geralmente detecta automaticamente...
# mas eh uma boa prática deixar explícito
spring.datasource.driver-class-name=org.postgresql.Driver

# ysuário e senha definida ao criar o banco
# coloquei em um .env para exemplo, então você não pode ver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.application.name=Persistencia
